/**
 * Learn batch H3 — lessons 11-15 (streets, 3-Bet, the maths), `docs/FISHTILT_CONTENT_PLAN.md`
 * §7 "H3".
 */
import type { LearnRecord } from '../../types.js';

export const LEARN_H3_RECORDS: readonly LearnRecord[] = [
  {
    kind: 'learn',
    id: 'flop-turn-river',
    slug: 'flop-turn-river',
    order: 11,
    title: '플랍 · 턴 · 리버, 카드는 이렇게 열립니다',
    description:
      '공용 카드 다섯 장이 3장, 1장, 1장으로 나뉘어 열리는 순서와 각 단계의 이름을 정리합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['street', 'board'],
    prerequisites: ['preflop'],
    relatedConcepts: [
      'term-preflop',
      'term-flop',
      'term-turn',
      'term-river',
      'term-board',
      'term-community-cards',
      'term-outs',
      // WP-S3-16: the postflop paragraph names the C-Bet once (the term's only contextual inbound).
      'term-c-bet',
    ],
    relatedTools: ['toolOuts', 'toolHandChecker'],
    relatedHands: [],
    nextLessons: ['three-bet'],
    relatedArticles: ['blog-playing-the-board', 'blog-outs-nine'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 6,
  },
  {
    kind: 'learn',
    id: 'three-bet',
    slug: 'three-bet',
    order: 12,
    title: '상대의 레이즈에 다시 레이즈 (3-Bet)',
    description:
      '왜 두 번째 레이즈를 3-Bet이라고 부르는지, 그리고 그 상황에서 무엇이 달라지는지 설명합니다.',
    level: 'INTERMEDIATE',
    topic: 'betting',
    concepts: ['three-bet', 'range', 'preflop'],
    prerequisites: ['preflop'],
    relatedConcepts: [
      'term-open-raise',
      'term-range',
      'term-three-bet',
      'term-four-bet',
      'term-big-blind',
      'term-button',
      'term-small-blind',
      'term-utg',
    ],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['equity'],
    relatedArticles: ['blog-why-called-3bet', 'blog-why-blinds-exist'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 5,
  },
  {
    kind: 'learn',
    id: 'equity',
    slug: 'equity',
    order: 13,
    title: '내 승률은 몇 퍼센트일까? (Equity)',
    description:
      '지금 이 패가 끝까지 갔을 때 팟에서 기대되는 몫을 뜻하는 말. 어떻게 세는지 예로 확인합니다.',
    level: 'BASIC',
    topic: 'equity',
    concepts: ['equity', 'probability'],
    prerequisites: ['flop-turn-river'],
    relatedConcepts: ['term-equity', 'term-pot', 'term-split-pot', 'term-showdown'],
    relatedTools: ['toolEquity'],
    relatedHands: ['hand-88', 'hand-aks'],
    nextLessons: ['pot-odds'],
    relatedArticles: ['blog-qq-vs-ak', 'blog-why-suited-matters'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 5,
  },
  {
    kind: 'learn',
    id: 'pot-odds',
    slug: 'pot-odds',
    order: 14,
    title: '콜할 값어치가 있을까? 팟오즈',
    description:
      '내야 하는 돈과 가져갈 수 있는 돈을 비교해, 콜에 필요한 최소 승률을 구하는 방법입니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['pot-odds', 'equity'],
    prerequisites: ['equity'],
    relatedConcepts: ['term-pot-odds', 'term-pot', 'term-equity', 'term-big-blind'],
    relatedTools: ['toolPotOdds', 'toolEquity'],
    relatedHands: ['hand-88'],
    nextLessons: ['outs'],
    relatedArticles: ['blog-pot-odds-quick', 'blog-outs-nine'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 6,
  },
  {
    kind: 'learn',
    id: 'outs',
    slug: 'outs',
    order: 15,
    title: '아직 남은 좋은 카드, 아웃츠',
    description:
      '내 패를 완성시켜 주는 카드가 몇 장 남았는지 세고, 그 카드가 나올 확률을 구합니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['outs', 'probability', 'draw'],
    prerequisites: ['pot-odds'],
    relatedConcepts: ['term-outs', 'term-draw', 'term-flush', 'term-straight', 'term-pot-odds'],
    relatedTools: ['toolOuts', 'toolEquity', 'toolPotOdds'],
    relatedHands: ['hand-aks'],
    nextLessons: [],
    relatedArticles: ['blog-outs-nine', 'blog-pot-odds-quick'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 6,
  },
];
