'use server';

/**
 * The post-session analysis server actions (ADR-0062).
 *
 * A server action is a public endpoint, so its input is untrusted and is re-validated from
 * scratch inside the service. These wrappers add nothing but the real database handle, the
 * real clock and `cryptoIdFactory` — every id and both timestamps a run records are supplied
 * from here, never generated by `@gto-self/db` (ADR-0040).
 *
 * Neither action is on a hand path. `runSessionAnalysisAction` is what the user gets by
 * pressing 세션 분석 및 반영 and then waiting for a summary (prompt §35 explicitly allows it
 * to be slower than the interactive Strategy panel); `getPlayerModelAction` is a profile
 * read. Nothing in `poker-core`'s action path awaits either (ADR-0043).
 *
 * Neither writes, reads or deletes raw hand history: the run's only write path is
 * `insertAnalysisResults`, which touches derived tables alone (prompt §33).
 */
import { cryptoIdFactory } from '@gto-self/shared';
import type {
  GetPlayerModelResult,
  RunSessionAnalysisResult,
  RunSessionAnalysisValue,
} from '../analysis-contract.js';
import { database } from '../db.js';
import { getPlayerModel as getPlayerModelIn, runSessionAnalysis } from '../analysis-service.js';
import { nowTimestamp } from '../session-service.js';

/**
 * Analyse one session: discover the players it dealt in, recompute each one's model from
 * their COMPLETE eligible history, and write the run in a single transaction.
 *
 * The parameter is typed for the caller's convenience only — the value crossing the network
 * is untrusted, and the service re-parses it.
 */
export async function runSessionAnalysisAction(
  input: RunSessionAnalysisValue,
): Promise<RunSessionAnalysisResult> {
  return runSessionAnalysis(database(), input, { ids: cryptoIdFactory, now: nowTimestamp });
}

/** One player's latest model snapshot (full content) plus their version list. */
export async function getPlayerModelAction(input: {
  playerId: string;
}): Promise<GetPlayerModelResult> {
  return getPlayerModelIn(database(), input);
}
