/**
 * Hands batch K1 — the five big pocket pairs (`aa`, `kk`, `qq`, `jj`, `tt`).
 *
 * WP-S3-13a split the former single `e3.ts` (all twenty priority hands,
 * `docs/FISHTILT_CONTENT_PLAN.md` §4) into four batch files matching the Stage 3 content
 * audit's batches (`docs/reports/stage3/3BETTILT_CONTENT_AUDIT.md` §5), so four content
 * agents can each own one file. Nothing about the records changed in the split: ids, slugs,
 * titles, relations and the registry-wide order (`index.ts` restores E3's original order) are
 * exactly what `e3.ts` carried.
 *
 * `title`s follow the `describeHandClassKorean` + " · " + handKey pattern
 * (`src/features/range/copy.ts`); `relatedTools` carries `toolStartingHand` and `toolEquity`
 * per §37/§4.2's fixed section 7.
 */
import type { HandRecord } from '../../types.js';

export const HAND_K1_RECORDS: readonly HandRecord[] = [
  {
    kind: 'hands',
    id: 'hand-aa',
    slug: 'aa',
    handKey: 'AA',
    title: '같은 숫자 두 장 (A 페어) · AA',
    description: 'A 두 장을 받은 경우. 169가지 시작 패 중 이 패가 어디에 자리하는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['pocket-pair', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-pocket-pair', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-kk'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-how-often-aa'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
  {
    kind: 'hands',
    id: 'hand-kk',
    slug: 'kk',
    handKey: 'KK',
    title: '같은 숫자 두 장 (K 페어) · KK',
    description: 'K 두 장을 받은 경우. 에이스 페어 다음 순위가 어디쯤인지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['pocket-pair', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-pocket-pair', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-aa', 'hand-qq'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-next-best-after-aa'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
  {
    kind: 'hands',
    id: 'hand-qq',
    slug: 'qq',
    handKey: 'QQ',
    title: '같은 숫자 두 장 (Q 페어) · QQ',
    description:
      'Q 두 장을 받은 경우. AK와 자주 비교되는 이 패가 순위표에서 어디에 있는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['pocket-pair', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-pocket-pair', 'term-combo', 'term-suited', 'term-offsuit'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-kk', 'hand-jj', 'hand-aks'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-qq-vs-ak'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
  {
    kind: 'hands',
    id: 'hand-jj',
    slug: 'jj',
    handKey: 'JJ',
    title: '같은 숫자 두 장 (J 페어) · JJ',
    description: 'J 두 장을 받은 경우. 포켓 페어가 표 대각선에서 어떻게 이어지는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['pocket-pair', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-pocket-pair', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-qq', 'hand-tt', 'hand-aks'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-next-best-after-aa'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'hands',
    id: 'hand-tt',
    slug: 'tt',
    handKey: 'TT',
    title: '같은 숫자 두 장 (10 페어) · TT',
    description: '10 두 장을 받은 경우. 중간 크기 포켓 페어가 표에서 어디쯤 자리하는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['pocket-pair', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-pocket-pair', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-jj', 'hand-99'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-next-best-after-aa'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
