/**
 * Hands batch K3 — the ace-high non-pairs (`aks`, `ako`, `aqs`, `aqo`, `ajs`). See `k1.ts`'s
 * module doc for the WP-S3-13a split; records are verbatim from the former `e3.ts`.
 *
 * `hand-aks` and `hand-ako` already existed (WP-G's seed) and are reused verbatim (id, slug,
 * title, relations) per `docs/FISHTILT_CONTENT_PLAN.md` §4's table. `hand-aks` was
 * additionally WP-G2's proof record for the `/hands` + `/hands/[hand]` templates.
 */
import type { HandRecord } from '../../types.js';

export const HAND_K3_RECORDS: readonly HandRecord[] = [
  {
    kind: 'hands',
    id: 'hand-aks',
    slug: 'aks',
    handKey: 'AKs',
    title: '같은 무늬의 A와 K · AKs',
    description:
      'A와 K를 같은 무늬로 받은 경우. 조합이 몇 가지인지, 표의 어디에 있는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-offsuit', 'term-combo', 'term-hand'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-ako'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-aks-vs-ako'],
    // WP-G2 proof record, prose replaced by E3 — see the module doc.
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'hands',
    id: 'hand-ako',
    slug: 'ako',
    handKey: 'AKo',
    title: '다른 무늬의 A와 K · AKo',
    description:
      'A와 K를 서로 다른 무늬로 받은 경우. 같은 무늬일 때와 무엇이 달라지는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['offsuit', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-offsuit', 'term-suited', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-aks'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-aks-vs-ako'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'hands',
    id: 'hand-aqs',
    slug: 'aqs',
    handKey: 'AQs',
    title: '같은 무늬의 A와 Q · AQs',
    description:
      'A와 Q를 같은 무늬로 받은 경우. AK와 비교해 조합과 순위가 어떻게 다른지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-aks', 'hand-aqo', 'hand-ajs', 'hand-77'],
    nextLessons: ['starting-hands'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'hands',
    id: 'hand-aqo',
    slug: 'aqo',
    handKey: 'AQo',
    title: '다른 무늬의 A와 Q · AQo',
    description:
      'A와 Q를 서로 다른 무늬로 받은 경우. 같은 숫자의 수티드 패와 무엇이 달라지는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['offsuit', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-offsuit', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-aqs', 'hand-ako', 'hand-kqs'],
    nextLessons: ['starting-hands'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'hands',
    id: 'hand-ajs',
    slug: 'ajs',
    handKey: 'AJs',
    title: '같은 무늬의 A와 J · AJs',
    description: 'A와 J를 같은 무늬로 받은 경우. 에이스가 들어간 수티드 패의 위치를 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-combo'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-aqs', 'hand-ako', 'hand-a5s'],
    nextLessons: ['starting-hands'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
