/**
 * Hands batch K4 — the suited broadways and suited connectors (`kqs`, `kjs`, `qjs`, `jts`,
 * `t9s`). See `k1.ts`'s module doc for the WP-S3-13a split; records are verbatim from the
 * former `e3.ts`.
 */
import type { HandRecord } from '../../types.js';

export const HAND_K4_RECORDS: readonly HandRecord[] = [
  {
    kind: 'hands',
    id: 'hand-kqs',
    slug: 'kqs',
    handKey: 'KQs',
    title: '같은 무늬의 K와 Q · KQs',
    description:
      'K와 Q를 같은 무늬로 받은 경우. 두 브로드웨이 카드가 만나면 순위가 어떻게 되는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited'],
    relatedTools: ['toolStartingHand', 'toolEquity', 'toolOuts'],
    relatedHands: ['hand-kjs', 'hand-aks'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-why-suited-matters'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
  {
    kind: 'hands',
    id: 'hand-kjs',
    slug: 'kjs',
    handKey: 'KJs',
    title: '같은 무늬의 K와 J · KJs',
    description: 'K와 J를 같은 무늬로 받은 경우. 이 패의 조합 수와 순위를 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-broadway', 'term-connector'],
    relatedTools: ['toolStartingHand', 'toolEquity'],
    relatedHands: ['hand-kqs', 'hand-qjs'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-why-suited-matters'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
  {
    kind: 'hands',
    id: 'hand-qjs',
    slug: 'qjs',
    handKey: 'QJs',
    title: '같은 무늬의 Q와 J · QJs',
    description:
      'Q와 J를 같은 무늬로 받은 경우. 연달아 있는 두 카드가 표에서 어디에 있는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-broadway', 'term-connector'],
    relatedTools: ['toolStartingHand', 'toolEquity', 'toolOuts'],
    relatedHands: ['hand-kjs', 'hand-jts', 'hand-kqs'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-why-suited-matters'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'hands',
    id: 'hand-jts',
    slug: 'jts',
    handKey: 'JTs',
    title: '같은 무늬의 J와 10 · JTs',
    description:
      'J와 10을 같은 무늬로 받은 경우. 연달아 있는 두 카드가 표에서 어디에 있는지 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-broadway', 'term-connector'],
    relatedTools: ['toolStartingHand', 'toolEquity', 'toolOuts'],
    relatedHands: ['hand-qjs', 'hand-t9s', 'hand-kjs', 'hand-tt'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-why-suited-matters'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
  {
    kind: 'hands',
    id: 'hand-t9s',
    slug: 't9s',
    handKey: 'T9s',
    title: '같은 무늬의 10과 9 · T9s',
    description: '10과 9를 같은 무늬로 받은 경우. 커넥터라 불리는 패의 순위를 확인합니다.',
    level: 'INTRO',
    topic: 'starting-hands',
    concepts: ['suited', 'starting-hand'],
    prerequisites: [],
    relatedConcepts: ['term-suited', 'term-broadway', 'term-connector'],
    relatedTools: ['toolStartingHand', 'toolEquity', 'toolOuts'],
    relatedHands: ['hand-jts', 'hand-22', 'hand-tt'],
    nextLessons: ['starting-hands'],
    relatedArticles: ['blog-why-suited-matters'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 3,
  },
];
