/**
 * Glossary batch G1 — 게임 구조 · 판과 돈 (8 terms). Category `game` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G1_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-ante',
    slug: 'ante',
    term: 'Ante',
    aliases: ['앤티', '안테', '앤티비'],
    title: '앤티 (Ante) — 모두가 내는 참가비',
    shortDefinition:
      '게임에 따라 참가자 전원이 매 판 내는 소액의 강제 베팅입니다. 앤티가 있는 게임도, 없는 게임도 있습니다.',
    description:
      '블라인드 외에 추가로 걷는 강제 베팅인 앤티가 무엇인지, 어떤 게임에 있는지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['ante', 'rules'],
    prerequisites: [],
    relatedConcepts: ['term-blind'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['holdem-basics'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-blind',
    slug: 'blind',
    term: 'Blind',
    aliases: ['블라인드', '블라인드 베팅', '강제 베팅'],
    title: '블라인드 (Blind) — 강제로 내는 돈',
    shortDefinition:
      '차례가 되기도 전에 강제로 내야 하는 돈을 말합니다. 스몰 블라인드와 빅 블라인드 두 자리가 냅니다.',
    description: '판마다 강제로 걸리는 돈인 블라인드가 왜 있는지, 누가 내는지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['blind', 'rules'],
    prerequisites: [],
    // `term-ante` is named in this entry's own `## 앤티와 함께 쓰이기도 합니다` section, so it
    // belongs under `이 글에 나온 말들` — and it was the only inbound link the ante entry had
    // anywhere on the site (WP-7b).
    relatedConcepts: ['term-big-blind', 'term-small-blind', 'term-ante'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['holdem-basics'],
    relatedArticles: ['blog-why-blinds-exist'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-big-blind',
    slug: 'big-blind',
    term: 'Big Blind',
    aliases: ['BB', '빅블라인드', '빅블', '빅 블라인드'],
    title: '빅 블라인드 (BB)',
    shortDefinition: '빅 블라인드 자리가 강제로 내는, 스몰 블라인드의 두 배인 돈을 말합니다.',
    description: '빅 블라인드가 얼마를 강제로 내는지, 왜 그 자리에 있는지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['blind', 'position'],
    prerequisites: [],
    relatedConcepts: ['term-small-blind', 'term-blind'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['positions-6max'],
    relatedArticles: ['blog-why-blinds-exist'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-small-blind',
    slug: 'small-blind',
    term: 'Small Blind',
    aliases: ['SB', '스몰블라인드', '스몰블', '스몰 블라인드'],
    title: '스몰 블라인드 (SB)',
    shortDefinition: '스몰 블라인드 자리가 강제로 내는, 빅 블라인드보다 적은 돈을 말합니다.',
    description: '스몰 블라인드가 얼마를 강제로 내는지, 빅 블라인드와 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['blind', 'position'],
    prerequisites: [],
    relatedConcepts: ['term-big-blind', 'term-blind', 'term-heads-up'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['positions-6max'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-stack',
    slug: 'stack',
    term: 'Stack',
    aliases: ['스택', '칩', '남은 칩', '스텍'],
    title: '스택 (Stack) — 내 앞의 칩',
    shortDefinition: '지금 내 앞에 쌓여 있는, 아직 걸지 않은 칩을 말합니다.',
    description: '스택이 무엇을 가리키는 말인지, 왜 중요한지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['stack', 'rules'],
    prerequisites: [],
    relatedConcepts: ['term-pot'],
    relatedTools: ['toolPotOdds'],
    relatedHands: [],
    nextLessons: ['holdem-basics'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-pot',
    slug: 'pot',
    term: 'Pot',
    aliases: ['팟', '폿', '판돈', '팟사이즈'],
    title: '팟 (Pot) — 판에 쌓인 돈',
    shortDefinition: '그 판에서 이미 걸린 돈이 모여 쌓인 것을 말합니다.',
    description: '팟이 어떻게 쌓이는지, 승자가 무엇을 가져가는지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['pot', 'rules'],
    prerequisites: [],
    relatedConcepts: ['term-stack', 'term-pot-odds'],
    relatedTools: ['toolPotOdds'],
    relatedHands: [],
    nextLessons: ['holdem-basics'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-heads-up',
    slug: 'heads-up',
    term: 'Heads-Up',
    aliases: ['헤즈업', '헤드업', 'heads up', '1대1', '일대일'],
    title: '헤즈업 (Heads-Up) — 둘만 남은 상황',
    shortDefinition: '둘만 남아서 서로 마주하는 상황을 말합니다.',
    description: '헤즈업이 6인 플레이와 무엇이 다른 상황인지 설명합니다.',
    level: 'BASIC',
    topic: 'rules',
    concepts: ['heads-up'],
    prerequisites: [],
    relatedConcepts: ['term-equity'],
    relatedTools: ['toolEquity'],
    relatedHands: [],
    nextLessons: ['equity'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-showdown',
    slug: 'showdown',
    term: 'Showdown',
    aliases: ['쇼다운', '쇼 다운', '카드 공개'],
    title: '쇼다운 (Showdown) — 카드를 열어 승부를 가리는 순간',
    shortDefinition: '남은 사람들이 카드를 열어 보여 승자를 가리는 순간을 말합니다.',
    description: '쇼다운이 언제 일어나는지, 항상 일어나는 것은 아니라는 점을 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['showdown', 'rules'],
    prerequisites: [],
    relatedConcepts: ['term-hand-ranking'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['holdem-basics'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
