/**
 * Glossary batch G2 — 게임 구조 · 스트리트와 보드 (6 terms). Category `game` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G2_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-preflop',
    slug: 'preflop',
    term: 'Preflop',
    aliases: ['프리플랍', '프리플롭', '프리플럽'],
    title: '프리플랍 (Preflop) — 공용 카드가 열리기 전',
    shortDefinition:
      '각자 두 장씩만 받고 공용 카드는 아직 한 장도 열리지 않은 상태에서 하는 첫 번째 베팅입니다.',
    description:
      '공용 카드가 열리기 전 첫 베팅 단계인 프리플랍. 이때 무엇을 보고 결정하는지 설명합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['preflop', 'street'],
    prerequisites: [],
    relatedConcepts: ['term-open-raise'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['preflop'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-flop',
    slug: 'flop',
    term: 'Flop',
    aliases: ['플랍', '플롭', '플럽'],
    title: '플랍 (Flop) — 처음 열리는 공용 카드 세 장',
    shortDefinition: '프리플랍 다음 처음 열리는 공용 카드 세 장을 말합니다.',
    description: '플랍이 왜 세 장씩 한번에 열리는지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['street', 'flop'],
    prerequisites: [],
    relatedConcepts: ['term-board', 'term-turn'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['flop-turn-river'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-turn',
    slug: 'turn',
    term: 'Turn',
    aliases: ['턴', '네번째 카드', '네 번째 카드'],
    title: '턴 (Turn) — 네 번째 공용 카드',
    shortDefinition: '플랍 다음 열리는 네 번째 공용 카드를 말합니다.',
    description: '턴이 플랍과 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['street', 'turn'],
    prerequisites: [],
    relatedConcepts: ['term-flop', 'term-river', 'term-outs'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['flop-turn-river'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-river',
    slug: 'river',
    term: 'River',
    aliases: ['리버', '마지막 카드', '리바'],
    title: '리버 (River) — 마지막 공용 카드',
    shortDefinition: '마지막으로 열리는 다섯 번째 공용 카드를 말합니다.',
    description: '리버가 왜 마지막 카드인지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['street', 'river'],
    prerequisites: [],
    relatedConcepts: ['term-turn'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['flop-turn-river'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-board',
    slug: 'board',
    term: 'Board',
    aliases: ['보드', '판', '공용 카드판'],
    title: '보드 (Board) — 테이블 가운데 깔린 카드',
    shortDefinition: '테이블 가운데 깔려 모두가 함께 쓰는 카드를 말합니다.',
    description: '보드가 몇 장인지, 언제 열리는지 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['board', 'street'],
    prerequisites: [],
    relatedConcepts: ['term-flop', 'term-community-cards'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['flop-turn-river'],
    relatedArticles: ['blog-playing-the-board'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-community-cards',
    slug: 'community-cards',
    term: 'Community Cards',
    aliases: ['커뮤니티 카드', '공용카드', '공용 카드', '공통 카드'],
    title: '커뮤니티 카드 (Community Cards) — 모두가 같이 쓰는 카드',
    shortDefinition: '보드를 이루는, 모든 플레이어가 공통으로 쓰는 카드를 말합니다.',
    description: '커뮤니티 카드가 보드와 같은 것을 가리키는 다른 이름이라는 것을 설명합니다.',
    level: 'INTRO',
    topic: 'rules',
    concepts: ['board', 'street'],
    prerequisites: [],
    relatedConcepts: ['term-board'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['flop-turn-river'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
