/**
 * Glossary batch G3 — 베팅·액션 · 기본 액션 (7 terms). Category `betting` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G3_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-action',
    slug: 'action',
    term: 'Action',
    aliases: ['액션', '행동', '차례'],
    title: '액션 (Action) — 내 차례의 행동',
    shortDefinition:
      '내 차례가 왔을 때 체크·베팅·콜·레이즈·폴드 중 하나를 고르는 그 선택 자체를 말합니다. "차례"가 선택할 기회라면, 액션은 그 기회에 실제로 고른 내용입니다.',
    description:
      '액션과 차례라는 두 말이 같이 쓰이며 헷갈리는 지점을 구분하고, 앞사람의 액션에 따라 이번 차례에 고를 수 있는 액션이 어떻게 달라지는지 정리합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['action'],
    prerequisites: [],
    relatedConcepts: ['term-check', 'term-bet', 'term-raise'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-check',
    slug: 'check',
    term: 'Check',
    aliases: ['체크', '첵'],
    title: '체크 (Check) — 돈을 걸지 않고 넘기기',
    shortDefinition:
      '돈을 걸지 않고 다음 사람에게 차례를 넘기는 행동을 말합니다. 아직 아무도 베팅하지 않았을 때만 가능합니다.',
    description: '체크가 언제 가능한지, 다른 행동과 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['action', 'check'],
    prerequisites: [],
    relatedConcepts: ['term-bet', 'term-call'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-bet',
    slug: 'bet',
    term: 'Bet',
    aliases: ['베팅', '벳', '배팅', '벧'],
    title: '베팅 (Bet) — 처음 돈을 거는 것',
    shortDefinition: '그 판에서 아직 아무도 걸지 않았을 때 처음으로 돈을 거는 행동을 말합니다.',
    description: '베팅이 체크·레이즈와 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['action', 'bet'],
    prerequisites: [],
    relatedConcepts: ['term-raise', 'term-call'],
    relatedTools: ['toolPotOdds'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-call',
    slug: 'call',
    term: 'Call',
    aliases: ['콜', '코울'],
    title: '콜 (Call) — 같은 금액 맞추기',
    shortDefinition: '상대가 건 금액과 같은 금액을 맞춰서 내는 행동을 말합니다.',
    description: '콜이 다른 행동과 무엇이 다른지, 언제 하는지 설명합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['action', 'call'],
    prerequisites: [],
    relatedConcepts: ['term-bet', 'term-pot-odds'],
    relatedTools: ['toolPotOdds'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-raise',
    slug: 'raise',
    term: 'Raise',
    aliases: ['레이즈', '레이스', '레이지'],
    title: '레이즈 (Raise) — 금액을 올리기',
    shortDefinition: '앞사람이 건 금액보다 더 많은 금액을 거는 행동을 말합니다.',
    description: '레이즈가 콜과 무엇이 다른지, 얼마나 올릴 수 있는지 설명합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['action', 'raise'],
    prerequisites: [],
    relatedConcepts: ['term-bet', 'term-open-raise'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-fold',
    slug: 'fold',
    term: 'Fold',
    aliases: ['폴드', '다이', '죽기', '폴딩'],
    title: '폴드 (Fold) — 패를 접는 것',
    shortDefinition: '패를 접고 그 판에서 빠지는 행동을 말합니다.',
    description: '폴드를 하면 그 판에서 무엇을 포기하는지 설명합니다.',
    level: 'INTRO',
    topic: 'betting',
    concepts: ['action', 'fold'],
    prerequisites: [],
    relatedConcepts: ['term-bet'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-all-in',
    slug: 'all-in',
    term: 'All-in',
    aliases: ['올인', '올 인', 'all in', '다이렉트'],
    title: '올인 (All-in) — 가진 칩 전부',
    shortDefinition: '가진 칩을 전부 걸고 더 이상 베팅할 것이 남지 않은 상태를 말합니다.',
    description: '칩을 전부 걸어 더 낼 것이 없는 상태인 올인이 무엇을 뜻하는지 설명합니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['all-in'],
    prerequisites: [],
    relatedConcepts: ['term-stack', 'term-bet'],
    relatedTools: ['toolPotOdds'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
