/**
 * Glossary batch G4 — 베팅·액션 · 프리플랍 베팅 이름과 통계 (8 terms). Category `betting` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G4_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-open-raise',
    slug: 'open-raise',
    term: 'Open Raise',
    aliases: ['오픈 레이즈', '오픈레이즈', '오픈', '첫 레이즈'],
    title: '오픈 레이즈 (Open Raise) — 아무도 들어오지 않았을 때 처음 거는 레이즈',
    shortDefinition:
      '앞사람이 모두 폴드해서 아직 아무도 판에 들어오지 않았을 때, 가장 먼저 레이즈하는 것을 말합니다.',
    description:
      '아직 아무도 참여하지 않은 판에 처음 레이즈를 거는 오픈 레이즈. 자리에 따라 무엇이 달라지는지 설명합니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['open-raise', 'preflop', 'position'],
    prerequisites: [],
    relatedConcepts: ['term-position', 'term-preflop'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['preflop'],
    relatedArticles: ['blog-btn-why-wide'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-limp',
    slug: 'limp',
    term: 'Limp',
    aliases: ['림프', '림핑', '리핑', '절뚝'],
    title: '림프 (Limp) — 레이즈 없이 최소 금액만 맞춰 들어가기',
    shortDefinition: '레이즈하지 않고 빅 블라인드와 같은 금액만 맞춰 들어가는 것을 말합니다.',
    description: '림프가 오픈 레이즈와 무엇이 다른지 설명합니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['limp', 'preflop'],
    prerequisites: [],
    relatedConcepts: ['term-open-raise'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['preflop'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-three-bet',
    slug: 'three-bet',
    term: '3-Bet',
    aliases: ['3벳', '쓰리벳', '쓰리 벳', '3-bet', '3bet', '삼벳'],
    title: '쓰리벳 (3-Bet) — 다시 거는 세 번째 레이즈',
    shortDefinition:
      '오픈 레이즈에 다시 레이즈하는 것을 말합니다. 빅 블라인드를 첫 번째, 오픈 레이즈를 두 번째로 세어 세 번째 벳이라는 뜻입니다.',
    description: '3-Bet이라는 이름이 어떻게 붙었는지, 세는 방법을 설명합니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['three-bet', 'bet-counting'],
    prerequisites: [],
    relatedConcepts: ['term-open-raise', 'term-four-bet'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['three-bet'],
    relatedArticles: ['blog-why-called-3bet'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-four-bet',
    slug: 'four-bet',
    term: '4-Bet',
    aliases: ['4벳', '포벳', '포 벳', '4-bet', '4bet'],
    title: '포벳 (4-Bet) — 그 다음 레이즈',
    shortDefinition: '3-Bet에 다시 레이즈하는 것을 말합니다.',
    description: '4-Bet이 3-Bet 다음에 오는 레이즈라는 것을 설명합니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['four-bet', 'bet-counting'],
    prerequisites: [],
    relatedConcepts: ['term-three-bet'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['three-bet'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-c-bet',
    slug: 'c-bet',
    term: 'C-Bet',
    aliases: ['씨벳', '시벳', 'cbet', 'continuation bet', '컨티뉴에이션 벳'],
    title: '컨티뉴에이션 벳 (C-Bet) — 앞선 공격자가 이어서 거는 베팅',
    shortDefinition:
      '프리플랍에서 마지막으로 레이즈한 사람이 플랍에서도 이어서 거는 베팅을 부르는 이름입니다. 얼마나 자주 하는 것이 좋은지는 이 사이트가 다루지 않습니다.',
    description: 'C-Bet이 어떤 상황의 베팅을 가리키는 이름인지 설명합니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['c-bet'],
    prerequisites: [],
    relatedConcepts: ['term-bet', 'term-flop'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['flop-turn-river'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-bluff',
    slug: 'bluff',
    term: 'Bluff',
    aliases: ['블러프', '블러핑', '뻥카'],
    title: '블러프 (Bluff) — 약한 패로 거는 베팅',
    shortDefinition: '지금 열면 이길 수 없는 패로 거는 베팅을 말합니다.',
    description: '블러프가 무엇을 뜻하는 말인지 설명합니다. 언제 해야 하는지는 다루지 않습니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['bluff'],
    prerequisites: [],
    relatedConcepts: ['term-bet'],
    relatedTools: ['practice'],
    relatedHands: [],
    nextLessons: ['poker-actions'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-vpip',
    slug: 'vpip',
    term: 'VPIP',
    aliases: ['브이핍', '자발적 참여율', 'voluntarily put in pot'],
    title: '판에 자발적으로 들어간 비율 (VPIP)',
    shortDefinition:
      '판에 자발적으로 돈을 걸고 참여한 비율을 세는 숫자입니다. 3BetTilt는 이 숫자를 계산하거나 추적하지 않습니다.',
    description: 'VPIP가 무엇을 세는 숫자인지 설명하고, 좋은 수치를 제시하지 않는 이유를 밝힙니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['vpip'],
    prerequisites: [],
    relatedConcepts: ['term-preflop', 'term-pfr'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['preflop'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-pfr',
    slug: 'pfr',
    term: 'PFR',
    aliases: ['피에프알', '프리플랍 레이즈율', 'preflop raise'],
    title: '프리플랍에서 레이즈한 비율 (PFR)',
    shortDefinition:
      '프리플랍에서 레이즈한 비율을 세는 숫자입니다. 3BetTilt는 이 숫자를 계산하거나 추적하지 않습니다.',
    description: 'PFR이 무엇을 세는 숫자인지 설명하고, 좋은 수치를 제시하지 않는 이유를 밝힙니다.',
    level: 'BASIC',
    topic: 'betting',
    concepts: ['pfr'],
    prerequisites: [],
    relatedConcepts: ['term-preflop', 'term-open-raise', 'term-vpip'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['preflop'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
