/**
 * Glossary batch G5 — 포지션 (5 terms). Category `position` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G5_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-position',
    slug: 'position',
    term: 'Position',
    aliases: ['포지션', '자리', '자리 순서'],
    title: '포지션 (Position) — 내 차례가 오는 자리',
    shortDefinition:
      '테이블에서 내가 몇 번째로 행동하는지를 뜻합니다. 늦게 행동할수록 앞사람들의 선택을 보고 결정할 수 있습니다.',
    description:
      '테이블에서의 행동 순서를 뜻하는 포지션. 왜 늦게 행동하는 자리가 유리한지 설명합니다.',
    level: 'BASIC',
    topic: 'position',
    concepts: ['position'],
    prerequisites: [],
    relatedConcepts: ['term-open-raise'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['position'],
    relatedArticles: ['blog-btn-why-wide'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-button',
    slug: 'button',
    term: 'Button',
    aliases: ['BTN', '버튼', '딜러 버튼', 'dealer button', '딜러버튼'],
    title: '버튼 (BTN)',
    shortDefinition: '그 판의 딜러 역할을 표시하는 자리로, 매 판 시계 방향으로 한 칸씩 이동합니다.',
    description: '버튼이 어떤 자리를 표시하는지, 왜 가장 늦게 행동하는 자리인지 설명합니다.',
    level: 'INTRO',
    topic: 'position',
    concepts: ['position'],
    prerequisites: [],
    relatedConcepts: ['term-position'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['positions-6max'],
    relatedArticles: ['blog-btn-why-wide'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-cutoff',
    slug: 'cutoff',
    term: 'Cutoff',
    aliases: ['CO', '컷오프', '컷 오프', '커트오프'],
    title: '컷오프 (CO)',
    shortDefinition: '버튼 바로 앞자리를 말합니다. 버튼 다음으로 늦게 행동합니다.',
    description: '컷오프가 버튼과 어떻게 다른 자리인지 설명합니다.',
    level: 'INTRO',
    topic: 'position',
    concepts: ['position'],
    prerequisites: [],
    relatedConcepts: ['term-button'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['positions-6max'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-hijack',
    slug: 'hijack',
    term: 'Hijack',
    aliases: ['HJ', '하이잭', '하이재크', '하이젝'],
    title: '하이잭 (HJ)',
    shortDefinition: '컷오프 바로 앞자리를 말합니다.',
    description: '하이잭이 6인 테이블에서 어디에 앉는 자리인지 설명합니다.',
    level: 'INTRO',
    topic: 'position',
    concepts: ['position'],
    prerequisites: [],
    relatedConcepts: ['term-cutoff'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['positions-6max'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-utg',
    slug: 'utg',
    term: 'UTG',
    aliases: ['언더더건', '언더 더 건', 'under the gun', '유티지'],
    title: '언더 더 건 (UTG) — 첫 번째 자리',
    seoTerm: 'UTG(언더 더 건)',
    shortDefinition: '6인 테이블에서 가장 먼저 행동하는 자리를 말합니다.',
    description: 'UTG가 왜 가장 먼저 행동하는 자리인지, 무엇이 불리한지 설명합니다.',
    level: 'INTRO',
    topic: 'position',
    concepts: ['position'],
    prerequisites: [],
    relatedConcepts: ['term-position'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['positions-6max'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-ip-oop',
    slug: 'ip-oop',
    term: 'IP / OOP',
    aliases: ['인포지션', '아웃오브포지션', 'IP', 'OOP', '인 포지션', '아웃 오브 포지션'],
    title: '인포지션 (IP / OOP) — 상대보다 늦게 행동하나요, 먼저 행동하나요',
    seoTerm: 'IP·OOP(인포지션·아웃오브포지션)',
    shortDefinition:
      '이번 핸드에서 상대보다 늦게 행동하면 인포지션(IP), 먼저 행동해야 하면 아웃오브포지션(OOP)이라고 부릅니다.',
    description: 'IP/OOP가 무엇을 기준으로 나뉘는지, 자리와 어떻게 다른지 설명합니다.',
    level: 'BASIC',
    topic: 'position',
    concepts: ['position'],
    prerequisites: [],
    relatedConcepts: ['term-position'],
    relatedTools: ['range'],
    relatedHands: [],
    nextLessons: ['position'],
    relatedArticles: ['blog-btn-why-wide'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
