/**
 * Glossary batch G6 — 카드·족보 · 아홉 족보 (10 terms). Category `hand-rankings` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G6_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-hand-ranking',
    slug: 'hand-ranking',
    term: 'Hand Ranking',
    aliases: ['족보', '핸드 랭킹', '핸드랭킹', 'hand rankings', '패의 순위'],
    title: '패의 순서, 족보 (Hand Ranking)',
    seoTerm: '족보',
    shortDefinition: '다섯 장으로 만드는 아홉 가지 족보 사이의 순서를 말합니다.',
    description: '핸드 랭킹이 무엇의 순서를 매기는 말인지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-kicker', 'term-split-pot'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-high-card',
    slug: 'high-card',
    term: 'High Card',
    aliases: ['하이카드', '하이 카드', '노페어', '탑카드'],
    title: '하이카드 (High Card) — 아무것도 만들어지지 않은 패',
    shortDefinition: '아무 족보도 만들어지지 않아 가장 높은 카드로만 겨루는 상태를 말합니다.',
    description: '하이카드가 왜 가장 낮은 순위인지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-hand-ranking', 'term-split-pot'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-one-pair',
    slug: 'one-pair',
    term: 'One Pair',
    aliases: ['원페어', '원 페어', '한 쌍', 'one pair'],
    title: '원페어 (One Pair) — 한 쌍',
    shortDefinition:
      '같은 숫자 카드 두 장으로 만든 한 쌍을 말합니다. 아홉 가지 족보 중 하이카드 다음으로 약합니다.',
    description:
      '원페어가 하이카드와 무엇이 다른지, 왜 아래에서 두 번째로 약한 족보인지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-two-pair', 'term-hand-ranking', 'term-kicker'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-two-pair',
    slug: 'two-pair',
    term: 'Two Pair',
    aliases: ['투페어', '투 페어'],
    title: '투페어 (Two Pair) — 두 쌍',
    shortDefinition: '숫자가 같은 두 쌍을 함께 만든 패를 말합니다.',
    description: '투페어가 원페어와 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-one-pair', 'term-hand-ranking'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-three-of-a-kind',
    slug: 'three-of-a-kind',
    term: 'Three of a Kind',
    aliases: ['트리플', '쓰리카드'],
    title: '트리플 (Three of a Kind) — 같은 숫자 세 장',
    shortDefinition: '같은 숫자 카드 세 장을 만든 패를 말합니다.',
    description: '쓰리 오브 어 카인드가 포켓 페어와 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-hand-ranking', 'term-full-house', 'term-set-vs-trips'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-set-vs-trips',
    slug: 'set-vs-trips',
    term: 'Set vs Trips',
    aliases: ['셋', 'set', 'trips', '트립스', '셋 vs 트립스'],
    title: '셋 vs 트립스 (Set vs Trips) — 셋과 트립스, 만들어지는 방식의 차이',
    seoTitle: '셋과 트립스 차이 | 홀덤·포커 용어 설명',
    shortDefinition:
      '족보로는 같은 쓰리 오브 어 카인드지만, 손패와 보드가 어떻게 섞였는지로 나누는 두 이름입니다.',
    description:
      '셋과 트립스가 족보상 같은 쓰리 오브 어 카인드를 만드는 서로 다른 두 경로임을 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-three-of-a-kind', 'term-hand-ranking'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-straight',
    slug: 'straight',
    term: 'Straight',
    aliases: ['스트레이트', '스트레잇', '줄', '스트레이트빨'],
    title: '스트레이트 (Straight) — 숫자가 연달아 다섯 장',
    shortDefinition: '숫자가 다섯 개 연달아 이어진 패를 말합니다. 무늬는 상관없습니다.',
    description: '스트레이트가 어떻게 완성되는지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-flush', 'term-hand-ranking', 'term-split-pot'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: ['blog-flush-vs-straight', 'blog-a2345-wheel'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-flush',
    slug: 'flush',
    term: 'Flush',
    aliases: ['플러시', '플러쉬', '플러시빨'],
    title: '플러시 (Flush) — 같은 무늬 다섯 장',
    shortDefinition: '같은 무늬 카드 다섯 장을 모은 패를 말합니다. 숫자 순서는 상관없습니다.',
    description: '플러시가 스트레이트와 무엇이 다른지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-straight', 'term-hand-ranking'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: ['blog-flush-vs-straight'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-full-house',
    slug: 'full-house',
    term: 'Full House',
    aliases: ['풀하우스', '풀 하우스', '풀', '풀하'],
    title: '풀하우스 (Full House) — 셋과 페어를 함께',
    shortDefinition: '같은 숫자 세 장과 다른 숫자의 페어를 함께 만든 패를 말합니다.',
    description: '풀하우스가 어떤 두 조각으로 이루어지는지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-flush', 'term-four-of-a-kind', 'term-hand-ranking'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: ['blog-full-house-vs-flush'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-four-of-a-kind',
    slug: 'four-of-a-kind',
    term: 'Four of a Kind',
    aliases: ['포카드', '포 카드', 'quads', '쿼즈'],
    title: '포카드 (Four of a Kind) — 같은 숫자 네 장',
    shortDefinition:
      '같은 숫자 카드 네 장을 만든 패를 말합니다. 풀하우스보다 강하고, 스트레이트 플러시보다는 약합니다.',
    description: '포카드가 풀하우스, 스트레이트 플러시와 강도 순서상 어디에 있는지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-full-house', 'term-hand-ranking'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-straight-flush',
    slug: 'straight-flush',
    term: 'Straight Flush',
    aliases: ['스트레이트플러시', '스트레이트 플러시', 'royal flush', '로열 플러시', '로티플'],
    title: '스트레이트 플러시 (Straight Flush) — 같은 무늬로 연달아 다섯 장',
    shortDefinition:
      '같은 무늬로 숫자가 다섯 개 연달아 이어진 패를 말합니다. 로열 플러시는 그중 가장 높은 것을 가리키는 이름입니다.',
    description: '스트레이트 플러시와 로열 플러시가 어떤 관계인지 설명합니다.',
    level: 'INTRO',
    topic: 'hand-strength',
    concepts: ['hand-ranking'],
    prerequisites: [],
    relatedConcepts: ['term-full-house', 'term-hand-ranking'],
    relatedTools: ['toolHandChecker'],
    relatedHands: [],
    nextLessons: ['hand-rankings'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
