/**
 * Glossary batch G8 — 확률·수학 (4 terms). Category `math` in
 * `categories.ts`, which is the source of truth for membership; this file only groups the
 * records so one content agent can own it (WP-S3-11 split of the former j1/j2 batches).
 *
 * Every record's `id`, `slug`, `aliases`, `shortDefinition` and relations moved here
 * verbatim. `batches.test.ts` gates this file: threshold, readMinutes, MDX map wiring,
 * `<Term>` and `<PokerCards>` validity, no strategy claims.
 */
import type { GlossaryRecord } from '../../types.js';

export const GLOSSARY_G8_RECORDS: readonly GlossaryRecord[] = [
  {
    kind: 'glossary',
    id: 'term-draw',
    slug: 'draw',
    term: 'Draw',
    aliases: ['드로우', '드로', '드로잉', '기다리는 패'],
    title: '드로우 (Draw) — 아직 완성되지 않은 패',
    shortDefinition: '아직 완성되지 않았지만 다음 카드로 완성될 수 있는 패를 말합니다.',
    description: '드로우가 무엇을 기다리는 상태인지 설명합니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['draw'],
    prerequisites: [],
    relatedConcepts: ['term-outs'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['outs'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-outs',
    slug: 'outs',
    term: 'Outs',
    aliases: ['Out', '아웃', '아웃츠', '아웃 카드', '아웃수'],
    title: '아웃츠 (Outs) — 내 패를 완성시키는 남은 카드',
    shortDefinition: '내 드로우를 완성시켜 주는, 아직 보지 못한 카드를 말합니다.',
    description: '아웃츠를 세는 방법과 확률로 바꾸는 법을 설명합니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['outs', 'draw'],
    prerequisites: [],
    relatedConcepts: ['term-draw', 'term-pot-odds'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['outs'],
    relatedArticles: ['blog-outs-nine'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-equity',
    slug: 'equity',
    term: 'Equity',
    aliases: ['에퀴티', '이쿼티', '승률', '내 승률', '이길 확률'],
    title: '에퀴티 (Equity) — 내 승률',
    shortDefinition: '지금 이 패가 끝까지 갔을 때 팟에서 기대되는 몫입니다.',
    description: '에퀴티가 무엇을 재는 숫자인지 설명합니다. 콜 여부는 다루지 않습니다.',
    level: 'BASIC',
    topic: 'equity',
    concepts: ['equity'],
    prerequisites: [],
    relatedConcepts: ['term-pot-odds'],
    relatedTools: ['toolEquity'],
    relatedHands: [],
    nextLessons: ['equity'],
    relatedArticles: ['blog-qq-vs-ak'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-pot-odds',
    slug: 'pot-odds',
    term: 'Pot Odds',
    aliases: ['팟오즈', '팟 오즈', '폿오즈', '팟 확률', 'pot odds'],
    title: '팟오즈 (Pot Odds) — 콜 값어치',
    shortDefinition:
      '내야 하는 돈과 가져갈 수 있는 돈을 비교해서 얻는, 콜에 필요한 최소 승률을 말합니다.',
    description: '팟오즈가 무엇을 비교해서 나오는 값인지 설명합니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['pot-odds'],
    prerequisites: [],
    relatedConcepts: ['term-equity', 'term-pot'],
    relatedTools: ['toolPotOdds'],
    relatedHands: [],
    nextLessons: ['pot-odds'],
    relatedArticles: ['blog-pot-odds-quick'],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-gutshot',
    slug: 'gutshot',
    term: 'Gutshot',
    aliases: [
      '거트샷',
      '거트샷 드로우',
      '거트샷 스트레이트 드로우',
      '인사이드 스트레이트 드로우',
      'inside straight draw',
    ],
    title: '거트샷 (Gutshot) — 한 장만 있으면 되는 스트레이트 드로우',
    shortDefinition:
      '이어지는 숫자 중 가운데 한 칸이 비어 있어서, 정확히 그 숫자 한 장만 나오면 완성되는 스트레이트 드로우입니다.',
    description: '거트샷이 어떤 스트레이트 드로우를 가리키는지, 아웃이 왜 4장뿐인지 설명합니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['draw', 'outs'],
    prerequisites: [],
    relatedConcepts: ['term-draw', 'term-outs', 'term-open-ended'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['outs'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
  {
    kind: 'glossary',
    id: 'term-open-ended',
    slug: 'open-ended',
    term: 'Open-Ended',
    aliases: [
      '오픈엔디드',
      '오픈엔디드 스트레이트 드로우',
      '양쪽 스트레이트 드로우',
      '양차',
      'open-ended straight draw',
    ],
    title: '오픈엔디드 (Open-Ended) — 양쪽으로 완성되는 스트레이트 드로우',
    shortDefinition:
      '이어지는 숫자 네 장이 나란히 있어서, 위아래 어느 쪽 숫자가 나와도 완성되는 스트레이트 드로우입니다.',
    description: '오픈엔디드가 거트샷과 무엇이 다른지, 아웃이 왜 8장인지 설명합니다.',
    level: 'BASIC',
    topic: 'odds',
    concepts: ['draw', 'outs'],
    prerequisites: [],
    relatedConcepts: ['term-draw', 'term-outs', 'term-gutshot'],
    relatedTools: ['toolOuts'],
    relatedHands: [],
    nextLessons: ['outs'],
    relatedArticles: [],
    status: 'PUBLISHED',
    indexable: true,
    readMinutes: 2,
  },
];
